### ISSUE TITLE
Conan package

### ISSUE THREAD

**Issue by ZaMaZaN4iK** [Morwenn/cpp-sort#121]
Hello @Morwenn !
Do you know about [Conan](https://github.com/conan-io/conan)?
[Conan](http://docs.conan.io/en/latest/) is modern dependency manager for C++. And will be great if your library will be available via package manager for other developers.

[Here](https://github.com/bincrafters/conan-templates) you can find example, how you can create package for the library. 

If you have any questions, just ask :-)

**Comment by Morwenn** [comment]
I know about Conan, but failed to use it the last time I tried: probably due to the fact that I am using MinGW-w64, and most of the libraries I needed weren't compiled and didn't have build rules for my platform. That said, I guess that it won't be that much of a problem to test with a header-only library :)

I will try to follow the example and ask if I have any questions (which will most likely be the case).

**Comment by Morwenn** [comment]
As expected, I already have a first question: it looks like I will most likely need to version the library, but I wanted "clean" versions for each supported C++; it wasn't a problem until there since it was mostly a fun personal project, but if I am to make it available through a package manager, I better make it look a bit more professional.

I will most likely have to add the additional C++17 features through `#ifdef`s to the C++14 version, which is a first step to have a single version usable everywhere, but I wish to keep "cleaner" versions for neer standards. One solution would be to version those as "c++14.x.y.z" and "c++17.x.y.z" for now, with "x.y.z" being usual semantic versioning numbers. I don't know whether this is a sensible solution. I wouldn't version the c++17 branch right away though since it's still experimental.

Do you have an opinion about that?

**Comment by uilianries** [comment]
Hi! @Morwenn 

You could use `options` for that:
```python
from conans import ConanFile, CMake, tools
 
class CppSortConan(ConanFile):
    name = "cpp-sort"
    version = "x.y.z"
    options = {"cpp_std": ["14", "17"}
    default_options = "cpp_std=14"
    generators = "cmake"
  
    def build(self):
        self._inject_magic_lines()
        conan_magic_lines = '''cmake_minimum_required(VERSION 3.1.0)
        include(${CMAKE_BINARY_DIR}/conanbuildinfo.cmake)
        conan_basic_setup()
        '''
        tools.replace_in_file("CMakeLists.txt", "cmake_minimum_required(VERSION 3.1.0)", 
        cmake = CMake(self)
        cmake.definitions["CPP_STD"] = self.options.cpp_std
        cmake.configure()
        cmake.build()
 
    def package(self):
        self.copy(pattern="*.h", src="include", dst="include")

    def package_id(self):
        self.info.header_only()
```

This example builds cpp-sort using an additional CMake definition. You could some like this to set your ifdef by cmake. Conan supports custom options, in this case I added `cpp_std` and only two values are allowed, "14" and "17".

As your project is header only I can't figure out some way to provide specific releases by c++ standard. Or you could generate new headers by the cpp_std, or the user needs to fill the ifdef when include your headers.

Regards.

**Comment by Morwenn** [comment]
@uilianries Thanks for the information. After having given it some more thought, I guess that I will just make the C++14 the main version, and maybe someday faaar in the future make a breaking change and set the main branch to C++17 (meanwhile I will conditionally support C++17 features on the main branch depending on the value of the `__cpluscplus` macro to make things simple). If people want to use the "clean" C++17 branch, they can just clone the repository and it shouldn't too complicated since it's a header-only library.

Those C++17 additions + a few minor things I'm supposed to remove will probably have to come before the 1.0.0 release though. I wouldn't want to introduce semantic versioning to bump straight to 2.0.0 after two weeks :)

Meanwhile I've started following the *Getting started* guide and am still halfway through it. With it, a few examples and a the page that shows how to create a header-only library, I already managed [to add a few basic files](https://github.com/Morwenn/cpp-sort/commit/c6d9417c5201063d3e0b0a3d9b238fd008668e2c) which seem to work with `conan create`. Now I still have a few things to do, but the first stone is already there.

Sooooo, here come the questions:
* Apparently the next step is to upload the package, I'm about to start reading about Bintray.
* My library only works with modern enough compilers. Do I have to declare with which compilers it might/might not be working, or does Conan not care about that? I couldn't find anything about that, but since my profile was originally configured to use MSVC, I quickly realized that if the `test_package` thing is run anywhere automagically it will probably need to know which compilers it can use.
* I didn't add rules to build the testsuite, I guess that the integrity test + my CI on GitHub is enough to be confident. Is that ok?
* Do I have to copy the license file to the project? I've read a few things about that and noticed that many projects on Bintray have a warning along the lines of "this project lacks a license" even though there was one in the GitHub repository. Which is the preferred way/destination to copy the license file?

That's pretty much it for now, thanks for the help :)

**Comment by Morwenn** [comment]
I created an account on Bintray and added a cpp-sort project: https://bintray.com/morwenn/cpp-sort

If I understand everything correctly, when I'm ready to release the 1.0.0 version, I'll just have to type the following commmand in my local repository:

```
conan upload cpp-sort/1.0.0@morwenn/stable --all -r=bintray_remote
```

Did I miss anything?

**Comment by uilianries** [comment]
Hi!

Sorry for my delay!

Answering your questions:

> My library only works with modern enough compilers. Do I have to declare with which compilers it might/might not be working, or does Conan not care about that? I couldn't find anything about that, but since my profile was originally configured to use MSVC, I quickly realized that if the test_package thing is run anywhere automagically it will probably need to know which compilers it can use.

Conan doesn't care about. If you really know which compilers are supported, you can add some rules on configure. Usually, I use this approach when I need to build projects that are supported only on few platforms.

```python
class CppSort(ConanFile):
    ...
    def configure(self):
        if self.settings.compiler == "Visual Studio" and self.settings.version <= "10":
            raise Exception("Dinosaurs are not allowed! Update your compiler now!")
        if self.settings.os == "Macos":
            raise Exception("Go home apple!")
```
This piece of code breaks when someone tries to build/install/run your recipe, under old msvc or apple.

> I didn't add rules to build the testsuite, I guess that the integrity test + my CI on GitHub is enough to be confident. Is that ok?

Not really. The test_package is to make sure that the package contains all necessary files, including headers and libraries (if has libraries). I strongly recommend add a test_package, this will work as a regression test for your recipe.

> Do I have to copy the license file to the project? I've read a few things about that and noticed that many projects on Bintray have a warning along the lines of "this project lacks a license" even though there was one in the GitHub repository. Which is the preferred way/destination to copy the license file?

Absolute right. In your specific case, you use MIT, that means "preservation of copyright and license notices" is required. [Conan recommends](http://docs.conan.io/en/latest/uploading_packages/bintray/conan_center_guide.html?highlight=conan-center#recipe-quality) to place all license files on a directory named "licenses"

> If I understand everything correctly, when I'm ready to release the 1.0.0 version, I'll just have to type the following commmand in my local repository:

It's totally correct. You just need to "create" your package, before to upload.

```
conan create . morwenn/stable
conan upload cpp-sort/1.0.0@morwenn/stable --all -r=bintray_remote
```

Also, it's possible to create/upload your package after a new release or when a new PR brings into master.

I'll fork your conan branch to add license stuff and a little job on Travis. You should receive my PR in few hours.

Regards!

**Comment by Morwenn** [comment]
@uilianries Ok, thanks for the clarifications :)

I think I already did the `test_package` stuff as long as the main `conanfile.py` in the linked branch, but probably have to remove the `import` thing since it doesn't look like I use it; I just wanted to make sure that I didn't have to upload the also testsuite. I will probably add a rule to reject MSVC since it's unable to compile the project right now.

**Comment by uilianries** [comment]
I just create the PR now.

The test suite will be not uploaded on Bintray. The package contains only your headers, license file and some Conan specific files. 

Regards!
